#ifndef PARKCONVERT_H
#define PARKCONVERT_H

#include "colorConvert.h"
#include "mapConvert.H"
#include "rideConvert.H"
#include "spriteConvert.H"
#include "messageConvert.h"
#include "animationConvert.h"
#include "bannerConvert.h"
#include "../rct1/sv4/sv4.h"
#include "../rct2/sv6/sv6.h"
//#include ""
//#include ""
//#include ""
//#include ""

ConvertPark(SV6_FILE *sv6,SV4_FILE *sv4);

#endif //PARKCONVERT_H
